part of admin.ui.pages.admin.debate.create_argument.operation_input;

class AdminDebateCreateArgumentOperationInputConfig {
  AdminDebateCreateArgumentOperationInputOperationCall operationCall;
  AdminDebateCreateArgumentOperationInputOperationCallSuccess operationCallSuccess;
  AdminDebateCreateArgumentOperationInputPostTitleChanged postTitleChanged;
  AdminDebateCreateArgumentOperationInputPostTypeChanged postTypeChanged;
  AdminDebateCreateArgumentOperationInputPostDescriptionChanged postDescriptionChanged;
  AdminDebateCreateArgumentOperationInputPageBackAction backAction;
  AdminDebateCreateArgumentOperationInputPageExtendActions extendActions;
  AdminDebateCreateArgumentOperationInputPageTitleGenerator titleGenerator;
}
