part of admin.ui.pages.admin.debate.close_debate.operation_output;

class AdminDebateCloseDebateOperationOutputConfig {
  AdminDebateCloseDebateOperationOutputPageBackAction backAction;
  AdminDebateCloseDebateOperationOutputPageExtendActions extendActions;
  AdminDebateCloseDebateOperationOutputPageTitleGenerator titleGenerator;
}
