part of admin.ui.pages.admin.dashboard.create_issue.operation_input;

class AdminDashboardCreateIssueOperationInputConfig {
  AdminDashboardCreateIssueOperationInputOperationCall operationCall;
  AdminDashboardCreateIssueOperationInputOperationCallSuccess operationCallSuccess;
  AdminDashboardCreateIssueOperationInputPostTitleChanged postTitleChanged;
  AdminDashboardCreateIssueOperationInputPostDescriptionChanged postDescriptionChanged;
  AdminDashboardCreateIssueOperationInputPageBackAction backAction;
  AdminDashboardCreateIssueOperationInputPageExtendActions extendActions;
  AdminDashboardCreateIssueOperationInputPageTitleGenerator titleGenerator;
}
