//////////////////////////////////////////////////////////////////////////////
// G E N E R A T E D    C L A S S
// ------------------------------
// Factory expression: #application.layoutTypes.?[original]
// Path expression: 'lib/'+#path(#application.actor.name)+'/ui/routes/router.dart'
// Template name: lib/ui/routes/router.dart.hbs
// Application: edemokracia::admin::Admin

import 'package:auto_route/auto_route.dart';
import 'package:auto_route/auto_route_annotations.dart';
import '../../app__config.dart';
import '../guards/auth_guard.dart';
import '../pages/package.dart';

const List<AutoRoute> bookmarkableRoutes = [
  CustomRoute(
    path: '/edemokracia-admin-admin-categories-table',
    page: AdminAdminCategoriesTablePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-admin-categories-view/:id',
    page: AdminAdminCategoriesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-admin-counties-table',
    page: AdminAdminCountiesTablePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-admin-counties-view/:id',
    page: AdminAdminCountiesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    initial: true,
    path: '/',
    page: AdminAdminDashboardhomeDashboardPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-admin-debates-table',
    page: AdminAdminDebatesTablePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-admin-debates-view/:id',
    page: AdminAdminDebatesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-admin-issues-table',
    page: AdminAdminIssuesTablePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-admin-issues-view/:id',
    page: AdminAdminIssuesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-admin-users-table',
    page: AdminAdminUsersTablePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-admin-users-view/:id',
    page: AdminAdminUsersViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-admin-votedefinitions-table',
    page: AdminAdminVoteDefinitionsTablePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-admin-votedefinitions-view/:id',
    page: AdminAdminVoteDefinitionsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
];

const List<AutoRoute> otherRoutes = [
  CustomRoute(
    path: '/edemokracia-city-districts-view',
    page: CityDistrictsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-comment-createdby-view',
    page: CommentCreatedByViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-comment-votes-view',
    page: CommentVotesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-con-comments-view',
    page: ConCommentsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-con-cons-view',
    page: ConConsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-con-createdby-view',
    page: ConCreatedByViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-con-pros-view',
    page: ConProsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-con-votes-view',
    page: ConVotesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-county-cities-view',
    page: CountyCitiesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-debate-comments-view',
    page: DebateCommentsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-debate-cons-view',
    page: DebateConsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-debate-createdby-view',
    page: DebateCreatedByViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-debate-debatevote-view',
    page: DebateDebateVoteViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-debate-issue-view',
    page: DebateIssueViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-debate-pros-view',
    page: DebateProsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-issue-attachments-view',
    page: IssueAttachmentsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-issue-categories-view',
    page: IssueCategoriesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-issue-comments-view',
    page: IssueCommentsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-issue-createdby-view',
    page: IssueCreatedByViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-issue-debates-view',
    page: IssueDebatesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-issue-owner-view',
    page: IssueOwnerViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-issuecategory-owner-view',
    page: IssueCategoryOwnerViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-issuecategory-subcategories-view',
    page: IssueCategorySubcategoriesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-pro-comments-view',
    page: ProCommentsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-pro-cons-view',
    page: ProConsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-pro-createdby-view',
    page: ProCreatedByViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-pro-pros-view',
    page: ProProsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-pro-votes-view',
    page: ProVotesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-simplevote-user-view',
    page: SimpleVoteUserViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-user-activitycities-view',
    page: UserActivityCitiesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-user-activitycounties-view',
    page: UserActivityCountiesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-user-activitydistricts-view',
    page: UserActivityDistrictsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-user-residentcity-view',
    page: UserResidentCityViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-user-residentcounty-view',
    page: UserResidentCountyViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-user-residentdistrict-view',
    page: UserResidentDistrictViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-user-votes-view',
    page: UserVotesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-votedefinition-voteentries-view',
    page: VoteDefinitionVoteEntriesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-voteentry-user-view',
    page: VoteEntryUserViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-voteentry-votedefinition-view',
    page: VoteEntryVoteDefinitionViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-admin-categories-create',
    page: AdminAdminCategoriesCreatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-admin-categories-edit',
    page: AdminAdminCategoriesUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-admin-counties-create',
    page: AdminAdminCountiesCreatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-admin-counties-edit',
    page: AdminAdminCountiesUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-admin-dashboardhome-view',
    page: AdminAdminDashboardhomeViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-admin-debates-edit',
    page: AdminAdminDebatesUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-admin-issues-edit',
    page: AdminAdminIssuesUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-admin-users-edit',
    page: AdminAdminUsersUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-admin-votedefinitions-edit',
    page: AdminAdminVoteDefinitionsUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-city-districts-create',
    page: AdminCityDistrictsCreatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-city-districts-edit',
    page: AdminCityDistrictsUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-city-districts-view',
    page: AdminCityDistrictsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-comment-createdby-view',
    page: AdminCommentCreatedByViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-comment-votes-create',
    page: AdminCommentVotesCreatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-comment-votes-edit',
    page: AdminCommentVotesUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-comment-votes-table',
    page: AdminCommentVotesTablePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-comment-votes-view',
    page: AdminCommentVotesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-con-comments-view',
    page: AdminConCommentsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-con-cons-edit',
    page: AdminConConsUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-con-cons-view',
    page: AdminConConsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-con-createcomment-input',
    page: AdminConCreateCommentOperationInputPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-con-createsubargument-input',
    page: AdminConCreateSubArgumentOperationInputPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-con-createdby-view',
    page: AdminConCreatedByViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-con-pros-edit',
    page: AdminConProsUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-con-pros-view',
    page: AdminConProsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-con-votes-table',
    page: AdminConVotesTablePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-con-votes-view',
    page: AdminConVotesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-county-cities-create',
    page: AdminCountyCitiesCreatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-county-cities-edit',
    page: AdminCountyCitiesUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-county-cities-view',
    page: AdminCountyCitiesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-dashboard-createissue-input',
    page: AdminDashboardCreateIssueOperationInputPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-dashboard-createissue-output',
    page: AdminDashboardCreateIssueOperationOutputPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-dashboard-createuser-input',
    page: AdminDashboardCreateUserOperationInputPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-dashboard-createuser-output',
    page: AdminDashboardCreateUserOperationOutputPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-dashboard-debates-view',
    page: AdminDashboardDebatesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-dashboard-issues-view',
    page: AdminDashboardIssuesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-debate-closedebate-input',
    page: AdminDebateCloseDebateOperationInputPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-debate-closedebate-output',
    page: AdminDebateCloseDebateOperationOutputPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-debate-comments-edit',
    page: AdminDebateCommentsUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-debate-comments-view',
    page: AdminDebateCommentsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-debate-cons-edit',
    page: AdminDebateConsUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-debate-cons-view',
    page: AdminDebateConsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-debate-createargument-input',
    page: AdminDebateCreateArgumentOperationInputPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-debate-createcomment-input',
    page: AdminDebateCreateCommentOperationInputPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-debate-createdby-view',
    page: AdminDebateCreatedByViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-debate-issue-view',
    page: AdminDebateIssueViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-debate-pros-edit',
    page: AdminDebateProsUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-debate-pros-view',
    page: AdminDebateProsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-debate-votedefinition-view',
    page: AdminDebateVoteDefinitionViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-issue-attachments-create',
    page: AdminIssueAttachmentsCreatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-issue-attachments-edit',
    page: AdminIssueAttachmentsUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-issue-attachments-view',
    page: AdminIssueAttachmentsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-issue-categories-view',
    page: AdminIssueCategoriesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-issue-comments-view',
    page: AdminIssueCommentsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-issue-createcomment-input',
    page: AdminIssueCreateCommentOperationInputPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-issue-createdebate-input',
    page: AdminIssueCreateDebateOperationInputPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-issue-createdebate-output',
    page: AdminIssueCreateDebateOperationOutputPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-issue-createdby-view',
    page: AdminIssueCreatedByViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-issue-debates-view',
    page: AdminIssueDebatesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-issue-owner-view',
    page: AdminIssueOwnerViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-issuecategory-owner-view',
    page: AdminIssueCategoryOwnerViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-issuecategory-subcategories-create',
    page: AdminIssueCategorySubcategoriesCreatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-issuecategory-subcategories-edit',
    page: AdminIssueCategorySubcategoriesUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-issuecategory-subcategories-view',
    page: AdminIssueCategorySubcategoriesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-pro-comments-view',
    page: AdminProCommentsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-pro-cons-edit',
    page: AdminProConsUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-pro-cons-view',
    page: AdminProConsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-pro-createcomment-input',
    page: AdminProCreateCommentOperationInputPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-pro-createsubargument-input',
    page: AdminProCreateSubArgumentOperationInputPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-pro-createdby-view',
    page: AdminProCreatedByViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-pro-pros-edit',
    page: AdminProProsUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-pro-pros-view',
    page: AdminProProsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-pro-votes-create',
    page: AdminProVotesCreatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-pro-votes-edit',
    page: AdminProVotesUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-pro-votes-table',
    page: AdminProVotesTablePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-pro-votes-view',
    page: AdminProVotesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-simplevote-user-view',
    page: AdminSimpleVoteUserViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-user-activitycities-edit',
    page: AdminUserActivityCitiesUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-user-activitycities-view',
    page: AdminUserActivityCitiesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-user-activitycounties-edit',
    page: AdminUserActivityCountiesUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-user-activitycounties-view',
    page: AdminUserActivityCountiesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-user-activitydistricts-edit',
    page: AdminUserActivityDistrictsUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-user-activitydistricts-view',
    page: AdminUserActivityDistrictsViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-user-residentcity-edit',
    page: AdminUserResidentCityUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-user-residentcity-view',
    page: AdminUserResidentCityViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-user-residentcounty-edit',
    page: AdminUserResidentCountyUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-user-residentcounty-view',
    page: AdminUserResidentCountyViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-user-residentdistrict-edit',
    page: AdminUserResidentDistrictUpdatePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-user-residentdistrict-view',
    page: AdminUserResidentDistrictViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-user-votes-table',
    page: AdminUserVotesTablePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-user-votes-view',
    page: AdminUserVotesViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-votedefinition-debate-table',
    page: AdminVoteDefinitionDebateTablePage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-votedefinition-debate-view',
    page: AdminVoteDefinitionDebateViewPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-votedefinition-voterating-input',
    page: AdminVoteDefinitionVoteRatingOperationInputPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-votedefinition-voteyesno-input',
    page: AdminVoteDefinitionVoteYesNoOperationInputPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
  CustomRoute(
    path: '/edemokracia-admin-votedefinition-voteyesnoabstain-input',
    page: AdminVoteDefinitionVoteYesNoAbstainOperationInputPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
    guards: [AuthGuard],
  ),
];

const List<AutoRoute> genericRoutes = [
  CustomRoute(
    page: EdemokraciaAdminAdminSettingsPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
  ),
  CustomRoute(
    page: EdemokraciaAdminAdminErrorPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
  ),
  CustomRoute(
    page: EdemokraciaAdminAdminBlankPage,
    transitionsBuilder: TransitionsBuilders.slideLeftWithFade,
  ),
];

const List<AutoRoute> additionalRoutes = AppConfig.additionalRoutes;

const List<AutoRoute> allRoutes = [...bookmarkableRoutes, ...otherRoutes, ...genericRoutes, ...additionalRoutes];

@MaterialAutoRouter(preferRelativeImports: true, routes: allRoutes)
class $Router {}
