part of admin.ui.pages.admin.pro.create_comment.operation_input;

class AdminProCreateCommentOperationInputConfig {
  AdminProCreateCommentOperationInputOperationCall operationCall;
  AdminProCreateCommentOperationInputOperationCallSuccess operationCallSuccess;
  AdminProCreateCommentOperationInputPostCommentChanged postCommentChanged;
  AdminProCreateCommentOperationInputPageBackAction backAction;
  AdminProCreateCommentOperationInputPageExtendActions extendActions;
  AdminProCreateCommentOperationInputPageTitleGenerator titleGenerator;
}
