part of admin.ui.pages.admin.debate.close_debate.operation_input;

class AdminDebateCloseDebateOperationInputConfig {
  AdminDebateCloseDebateOperationInputOperationCall operationCall;
  AdminDebateCloseDebateOperationInputOperationCallSuccess operationCallSuccess;
  AdminDebateCloseDebateOperationInputPostVoteTypeChanged postVoteTypeChanged;
  AdminDebateCloseDebateOperationInputPostCloseAtChanged postCloseAtChanged;
  AdminDebateCloseDebateOperationInputPostTitleChanged postTitleChanged;
  AdminDebateCloseDebateOperationInputPostDescriptionChanged postDescriptionChanged;
  AdminDebateCloseDebateOperationInputPageBackAction backAction;
  AdminDebateCloseDebateOperationInputPageExtendActions extendActions;
  AdminDebateCloseDebateOperationInputPageTitleGenerator titleGenerator;
}
