part of admin.ui.pages.admin.vote_definition.vote_rating.operation_input;

class AdminVoteDefinitionVoteRatingOperationInputConfig {
  AdminVoteDefinitionVoteRatingOperationInputOperationCall operationCall;
  AdminVoteDefinitionVoteRatingOperationInputOperationCallSuccess operationCallSuccess;
  AdminVoteDefinitionVoteRatingOperationInputPageBackAction backAction;
  AdminVoteDefinitionVoteRatingOperationInputPageExtendActions extendActions;
  AdminVoteDefinitionVoteRatingOperationInputPageTitleGenerator titleGenerator;
}
