part of admin.ui.pages.admin.debate.create_comment.operation_input;

class AdminDebateCreateCommentOperationInputConfig {
  AdminDebateCreateCommentOperationInputOperationCall operationCall;
  AdminDebateCreateCommentOperationInputOperationCallSuccess operationCallSuccess;
  AdminDebateCreateCommentOperationInputPostCommentChanged postCommentChanged;
  AdminDebateCreateCommentOperationInputPageBackAction backAction;
  AdminDebateCreateCommentOperationInputPageExtendActions extendActions;
  AdminDebateCreateCommentOperationInputPageTitleGenerator titleGenerator;
}
