part of admin.ui.pages.admin.con.create_sub_argument.operation_input;

class AdminConCreateSubArgumentOperationInputConfig {
  AdminConCreateSubArgumentOperationInputOperationCall operationCall;
  AdminConCreateSubArgumentOperationInputOperationCallSuccess operationCallSuccess;
  AdminConCreateSubArgumentOperationInputPostTitleChanged postTitleChanged;
  AdminConCreateSubArgumentOperationInputPostTypeChanged postTypeChanged;
  AdminConCreateSubArgumentOperationInputPostDescriptionChanged postDescriptionChanged;
  AdminConCreateSubArgumentOperationInputPageBackAction backAction;
  AdminConCreateSubArgumentOperationInputPageExtendActions extendActions;
  AdminConCreateSubArgumentOperationInputPageTitleGenerator titleGenerator;
}
