part of admin.ui.pages.admin.dashboard.create_user.operation_input;

class AdminDashboardCreateUserOperationInputConfig {
  AdminDashboardCreateUserOperationInputOperationCall operationCall;
  AdminDashboardCreateUserOperationInputOperationCallSuccess operationCallSuccess;
  AdminDashboardCreateUserOperationInputPostUserNameChanged postUserNameChanged;
  AdminDashboardCreateUserOperationInputPostHasAdminAccessChanged postHasAdminAccessChanged;
  AdminDashboardCreateUserOperationInputPostFirstNameChanged postFirstNameChanged;
  AdminDashboardCreateUserOperationInputPostLastNameChanged postLastNameChanged;
  AdminDashboardCreateUserOperationInputPostEmailChanged postEmailChanged;
  AdminDashboardCreateUserOperationInputPostPhoneChanged postPhoneChanged;
  AdminDashboardCreateUserOperationInputPageBackAction backAction;
  AdminDashboardCreateUserOperationInputPageExtendActions extendActions;
  AdminDashboardCreateUserOperationInputPageTitleGenerator titleGenerator;
}
